name: dispenser_obat_pintar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shimmer: ^3.0.0
  mqtt_client: ^10.3.1
  supabase_flutter: ^2.8.0
  fl_chart: ^1.2.0
  google_fonts: ^6.2.1
  cross_file: ^0.3.4+2
  path_provider: ^2.1.5
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"

  fullscreen: true

flutter:
  assets:
    - assets/images/

  uses-material-design: true
